import { useState,type FormEvent } from "react";
import { Activity,ArrowRight,LockKeyhole,ShieldCheck,Stethoscope } from "lucide-react";
import { api } from "./api";
import type { User } from "./types";
export default function Login({onLogin}:{onLogin:(token:string,user:User)=>void}){
  const[email,setEmail]=useState("admin@careflow.demo"),[password,setPassword]=useState("demo1234"),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");try{const r=await api<{token:string;user:User}>("/auth/login",{method:"POST",body:JSON.stringify({email,password})});onLogin(r.token,r.user)}catch{setError("Could not sign in. Check the demo credentials.")}finally{setLoading(false)}}
  return <div className="login-page"><section className="login-story"><div className="brand light"><span className="brand-mark"><Activity/></span><span>CareFlow<small>Clinical operations</small></span></div><div className="story-copy"><span className="eyebrow">COORDINATED CARE, CLEARLY</span><h1>Every workflow.<br/>One calm workspace.</h1><p>A portfolio demonstration of secure clinical operations, built around traceability, reliable handoffs and practical team workflows.</p><div className="story-points"><span><ShieldCheck/>Role-based access</span><span><Stethoscope/>Connected care workflows</span><span><LockKeyhole/>Auditable changes</span></div></div><small className="disclaimer">Demonstration only. Uses fictional data and is not intended for clinical use.</small></section><section className="login-panel"><form onSubmit={submit}><div className="mobile-logo"><Activity/> CareFlow</div><span className="eyebrow">WELCOME BACK</span><h2>Sign in to your workspace</h2><p>Use the prefilled administrator account to explore the demo.</p><label>Email address<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary wide" disabled={loading}>{loading?"Signing in…":"Sign in"}<ArrowRight/></button><div className="demo-note"><strong>Demo credentials</strong><span>admin@careflow.demo / demo1234</span></div></form></section></div>
}
